# Generated by Django 4.1.3 on 2023-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_messages', models.ManyToManyField(related_name='related_users', to='chat.message')),
            ],
        ),
    ]
