# Generated by Django 4.1.3 on 2023-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('unreadMessages', models.ManyToManyField(related_name='related_users', to='chat.message')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
