# Generated by Django 4.1.3 on 2023-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isLoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
