# Generated by Django 4.1.3 on 2023-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_isloggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isLoggedIn',
            field=models.BooleanField(default=True),
        ),
    ]
